### ISSUE TITLE
Create button fails

### ISSUE THREAD

**Issue by oumukoro** [jariq/Pkcs11Admin#13]
Every time the create button is clicked on, it stops the entire program and stops working.

**Comment by jariq** [comment]
Sounds like a bug in unmanaged PKCS#11 library but we need to gather logs to confirm that. Could you please enable logging, try to create object again and share the last call from the logs?

You can enable logging in "Load PKCS#11 library" window:

![image](https://user-images.githubusercontent.com/1163818/30830682-132bce54-a245-11e7-8beb-4d9d9eae0652.png)

Please note that in order to get logging working you will need to have [Visual C++ Redistributable for Visual Studio 2015](http://www.microsoft.com/en-us/download/details.aspx?id=48145) to be installed on the target system.

Correct call to `C_CreateObject` function should be similar to this:

```
0x0000121c : 0x000024c8 : ****************************** 2017-09-25 23:03:22 ***
0x0000121c : 0x000024c8 : Calling C_CreateObject
0x0000121c : 0x000024c8 : Input
0x0000121c : 0x000024c8 :  hSession: 10
0x0000121c : 0x000024c8 :  pTemplate: 00000177ADF18C50
0x0000121c : 0x000024c8 :  ulCount: 6
0x0000121c : 0x000024c8 :   *** Begin attribute template ***
0x0000121c : 0x000024c8 :   Attribute 0
0x0000121c : 0x000024c8 :    Attribute: 0 (CKA_CLASS)
0x0000121c : 0x000024c8 :    pValue: 00000177A986A3A0
0x0000121c : 0x000024c8 :    ulValueLen: 4
0x0000121c : 0x000024c8 :    *pValue: HEX(00000000)
0x0000121c : 0x000024c8 :   Attribute 1
0x0000121c : 0x000024c8 :    Attribute: 1 (CKA_TOKEN)
0x0000121c : 0x000024c8 :    pValue: 00000177A986A350
0x0000121c : 0x000024c8 :    ulValueLen: 1
0x0000121c : 0x000024c8 :    *pValue: HEX(01)
0x0000121c : 0x000024c8 :   Attribute 2
0x0000121c : 0x000024c8 :    Attribute: 2 (CKA_PRIVATE)
0x0000121c : 0x000024c8 :    pValue: 00000177A986A2D0
0x0000121c : 0x000024c8 :    ulValueLen: 1
0x0000121c : 0x000024c8 :    *pValue: HEX(00)
0x0000121c : 0x000024c8 :   Attribute 3
0x0000121c : 0x000024c8 :    Attribute: 368 (CKA_MODIFIABLE)
0x0000121c : 0x000024c8 :    pValue: 00000177A986A320
0x0000121c : 0x000024c8 :    ulValueLen: 1
0x0000121c : 0x000024c8 :    *pValue: HEX(01)
0x0000121c : 0x000024c8 :   Attribute 4
0x0000121c : 0x000024c8 :    Attribute: 3 (CKA_LABEL)
0x0000121c : 0x000024c8 :    pValue: 00000177ADECD990
0x0000121c : 0x000024c8 :    ulValueLen: 10
0x0000121c : 0x000024c8 :    *pValue: HEX(54657374206C6162656C)
0x0000121c : 0x000024c8 :   Attribute 5
0x0000121c : 0x000024c8 :    Attribute: 17 (CKA_VALUE)
0x0000121c : 0x000024c8 :    pValue: 00000177ADECDC10
0x0000121c : 0x000024c8 :    ulValueLen: 12
0x0000121c : 0x000024c8 :    *pValue: HEX(5465737420636F6E74656E74)
0x0000121c : 0x000024c8 :   *** End attribute template ***
0x0000121c : 0x000024c8 :  phObject: 0000001294BFD428
0x0000121c : 0x000024c8 :  *phObject: 0
0x0000121c : 0x000024c8 : Output
0x0000121c : 0x000024c8 :  phObject: 0000001294BFD428
0x0000121c : 0x000024c8 :  *phObject: 11
0x0000121c : 0x000024c8 : Returning 0 (CKR_OK)
```

Please note that log file may contain sensitive information so share only the last call here.

**Comment by oumukoro** [comment]
Hi, 
Thanks for your response. When I "enable logging" I get the same error and the application closes. I have VC installed

**Comment by jariq** [comment]
Do you get the same error when you are creating the object or right after you click "OK" in "Load PKCS#11 library" window?

**Comment by oumukoro** [comment]
When I click create.

**Comment by jariq** [comment]
OK that means logging worked. Could you please post here the contents of the log file `C:\Users\<your_username>\Documents\Pkcs11Admin.log` (it is in your "Documents" folder). The most interesting is part of the file from line containing "Calling C_CreateObject" up to the end of log file.

**Comment by oumukoro** [comment]
Hi, now I'm faced with a different issue. Do you have pkcs11-dump for windows? Thanks.
Here's the log:
Calling C_GetSlotList
0x00003280 : 0x000041ac : Input
0x00003280 : 0x000041ac :  tokenPresent: 0
0x00003280 : 0x000041ac :  pSlotList: 0000000000000000
0x00003280 : 0x000041ac :  pulCount: 00000090FC3BF058
0x00003280 : 0x000041ac :  *pulCount: 0
0x00003280 : 0x000041ac : Output
0x00003280 : 0x000041ac :  pSlotList: 0000000000000000
0x00003280 : 0x000041ac :  pulCount: 00000090FC3BF058
0x00003280 : 0x000041ac :  *pulCount: 0
0x00003280 : 0x000041ac : Returning 0 (CKR_OK)

**Comment by jariq** [comment]
> Do you have pkcs11-dump for windows?

Nope. Never heard of it before.

> Here's the log:

Is that the last entry in the log file? I don't think I can further analyze your problem without having access to the full log file. Please consider sending it to me privately to jaroslav.imrich@gmail.com.

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
