### ISSUE TITLE
Tool dies when trying to login user, when talking to the CryptoServer Simulator

### ISSUE THREAD

**Issue by rpwilliamson** [jariq/Pkcs11Admin#19]
SPD'd ("sudden program death") This is a build today, using 64bit windows.  It displays slots, tokens, etc, but when trying to log in to the slot as the user, program death.

I'll try to get some log files.  In the mean time, you can download the Utimaco HSM simulator from the Utimaco support portal/Simulator download request.  Can take two days to get approval.

**Comment by jariq** [comment]
@rpwilliamson have you managed to gather the logs?

**Comment by jariq** [comment]
Closing because of 20+ days without a response.
