### ISSUE TITLE
Unable to get pointer for C_GetFunctionList function

### ISSUE THREAD

**Issue by gsanchez27** [jariq/Pkcs11Admin#28]
Hello,

Just started trying to explore pkcs11interop and pkcs11 admintool.

I just encounter an error when loading the pkcs11interop.dll in pkcs11 admin tool

![Shot 035](https://user-images.githubusercontent.com/5301578/91168905-fc7c9880-e708-11ea-8f73-2d4575ece308.png)

**Comment by jariq** [comment]
Are you sure you're loading PKCS#11 library? It's location on the screenshot seems to be quite unusual.

**Comment by gsanchez27** [comment]
@jariq 

Thank you for your help. 

My bad, I was loading the "PKCS#11interop.dll" instead of loading the "softhsm2.dll".

After loading "softhsm2.dll" the app works fine now.
