### ISSUE TITLE
Program crashes when creating AES Key on NitroHSM with CKA_ID Checked

### ISSUE THREAD

**Issue by JGPorteous** [jariq/Pkcs11Admin#30]
The program crashes when creating AES Key on NitroHSM with CKA_ID Checked.
Library used: c:\windows\system32\sc-hsm-pkcs11.dll

I would like to do some more testing with other HSM systems before suggesting a code fix for this, hoping it's simple error handling.

I know with the NitroHSM with command line tools, it doesn't like it when you specify an ID (CKA_ID).

**Comment by JGPorteous** [comment]
Tested with default value of CKA_ID as empty on a Gemalto Luna - problem doesn't occur and AES key created successfuly.

**Comment by jariq** [comment]
> The program crashes when creating AES Key on NitroHSM with CKA_ID Checked.

Could you please describe "program crashes" in more details? Does it display any error message?

> I know with the NitroHSM with command line tools, it doesn't like it when you specify an ID (CKA_ID).

Different libraries require different attributes to be provided. That's why there's a checkbox so you can solve this from GUI.

**Comment by jariq** [comment]
Closing after 14+ days of inactivity.
