### ISSUE TITLE
Edit Attributes doesn't always update

### ISSUE THREAD

**Issue by JGPorteous** [jariq/Pkcs11Admin#31]
Editing attributes updates in application, but not necessarily in the HSM.

Maybe add a refresh from the HSM once the attributes are updated - and/or additional validation for update and post refresh checks?

**Comment by jariq** [comment]
Does this button solve your problem?

![image](https://user-images.githubusercontent.com/1163818/105693301-d77e9280-5eff-11eb-97c8-648333c33afa.png)

**Comment by jariq** [comment]
Closing after 14+ days of inactivity.
