### ISSUE TITLE
Problem creating new data object in virtual smart card

### ISSUE THREAD

**Issue by FelisLynx** [jariq/Pkcs11Admin#32]
Hi,
I have created a TPM **virtual smart card** in Windows 10 with **tpmvscmgr**
And I'm using **OpenSC project** opensc-pkcs11.dll as my lib.
In **Pkcs11Admin 0.5.0** I can login into token using my pin, I can create RSA keys successfully.
But when I'm trying to create a new data object it returns error: **Method C_CreateObject returned CKR_DATA_INVALID**

I tried different configurations, checked and unchecked attributes, tried valid DER formatted strings, and nothing helps.
Is it me doing something wrong, or OpenSC bug, or Pkcs11Admin?

**Comment by ElMostafaIdrassi** [comment]
I don't think Windows Virtual Smart Cards allow for the creation of anything other than RSA keys.
