### ISSUE TITLE
Where is locate the PKCS#11 .DLL Library?

### ISSUE THREAD

**Issue by mtorres-root** [jariq/Pkcs11Admin#36]
hi, i have dealt with various DDL such as SoftHSM2, SmartKeyKmsClient, OpenSC

But none works for scr3310v2 (identity card reader)

https://support.identiv.com/scr3310v2/

Search among the drivers, device files, other publications; but I don't know if I'm missing a step; or the dll is not correct; or you have to do something with the slots or the login to get the information.

Note using: SmartPCSCDiag.exe or pcscdiag.exe (Smart PC / SC Diagnostic) https://support.identiv.com/utilities-and-diagnostic-tools-for-smart-card-readers/

In the if it detects the card and the device (same when I withdraw it)

But I wanted to use the administrator but I can't find the DLL anywhere.

Please Help

**Comment by jariq** [comment]
PKCS#11 library is not driver for card reader, but **driver for the card**. You usually insert card into any PC/SC compatible reader, load PKCS#11 library provided by **card vendor** and you are good to go.

**Comment by mtorres-root** [comment]
So... 

You say 
![image](https://user-images.githubusercontent.com/74983767/134780426-1d9d834c-d845-4e69-924e-79b36300e0a8.png)

In this case, do I need to find this DLL or just put the Hardware and this detects the DLL as necessary?

**Comment by jariq** [comment]
It usually works this way:
1. You buy a smartcard that comes with a software a.k.a middleware and documentation
2. Insert the card into any PC/SC compatible reader
3. Install the software a.k.a. middlware provided by smartcard vendor
4. Read the documentation provided by smartcard vendor to find out the path to PKCS#11 library that was installed in step 3
5. Use any PKCS#11 compatible application with the PKCS#11 library provided by smartcard vendor

**Comment by jariq** [comment]
Closing after 14+ days of inactivity.
