### ISSUE TITLE
Deleted my PrivateKey

### ISSUE THREAD

**Issue by AymanTalaat** [jariq/Pkcs11Admin#38]
Hi .. 
I have an ePass2003 token that contains a certificate and a public and private keys
I don't know what exactly happened but it seems that I destroyed an object handle that contains the private Key ... :( 
and now I can see in the ePass2003  token manager   the certificate is there and the public key is there but no private keys
is it possible to re-generate a private key for the same certificate without returning to the CA or the company that issues the certificate ?

**Comment by jariq** [comment]
First of all, private key objects are usually visible only after you login to your token.  
If you are not logged in then you usually see just public objects such as certificates and public keys.  
Are you sure you are logged in?

However, if you managed to somehow delete private key, then the answer is: no, it cannot be restored.

**Comment by AymanTalaat** [comment]
thanks a lot for your care , I did logged in before trying to read the private key to sign a document
 but is it possible to generate a new one on the same repository (the issued certificate on the smart card ?) using the existing public key parameters
