### ISSUE TITLE
C_Finalize is never invoked

### ISSUE THREAD

**Issue by helpcrypto** [jariq/Pkcs11Admin#4]
Using pkcs11-spy, I don't see a C_Finalize call when closing the application, neither when changing between libraries.

**Comment by jariq** [comment]
Thanks for reporting! Call was really missing when the app was being closed. I have fixed it in 3f6ec8faf3a77358d9d2cf4ad84881071ecbf140. However my code review and testing with pkcs11-logger shows that C_Finalize is being called when the loaded library is changed. Are you sure you did not overlook the call in your log file?

**Comment by helpcrypto** [comment]
Probably did. Will test again and reopen this if I confirm the bad behaviour. Otherwise, consider it closed. Thanks.
