### ISSUE TITLE
src/build.sh: use "set -e" instead of " || exit"

### ISSUE THREAD

**Issue by LudovicRousseau** [jariq/Pkcs11Admin#7]
set -e
      " Exit immediately if a simple command (see SHELL  GRAMMAR above) exits with a non-zero status.  The shell does not exit if the command that fails is part  of  the  command list  immediately  following  a  while or until keyword, part of the test in an if statement, part of a && or  || list, or if the command's return value is being inverted via !.  A trap on ERR, if set, is  executed  before  the shell exits. "

If you use "set -e" at the beginning of your shell script then any command returning in error will make the script to exit. No need to use: "command  || exit" on each line.

**Comment by jariq** [comment]
Thanks!
