### ISSUE TITLE
Can't find the specified module (invalid path character?)

### ISSUE THREAD

**Issue by helpcrypto** [jariq/Pkcs11Admin#8]
I'm not 100% sure its not an issue on my side/config (after all, this is a pkcs11 testing utility) but using 0.2.0 and a library path like "C:\Program Files\Gemalto\IDGo 800 PKCS#11\IDPrimePKCS11.dll" I'm getting: "Can't find the specified module"

Can you double check path issues?
Thanks!

UPDATE:
Seems the problem happens only with pkcs11-helper enabled.
The current path is C:\Users\user\Desktop\pkcs11admin\Pkcs11Admin-0.2.0\Pkcs11Admin-0.2.0\pkcs11-logger\pkcs11-logger-x86.dll

**Comment by helpcrypto** [comment]
Seems the problem happens only with pkcs11-helper enabled.

The current path is C:\Users\user\Desktop\pkcs11admin\Pkcs11Admin-0.2.0\Pkcs11Admin-0.2.0\pkcs11-logger\pkcs11-logger-x86.dll

**Comment by jariq** [comment]
I am unable to replicate the issue. I have tried with exactly same paths and no error occurred regardless of whether logging was enabled or disabled.

**Comment by helpcrypto** [comment]
I'll try again next week and give you more feedback.
In the meantime, you can develop a more-verbose logging version.

Regards.

**Comment by jariq** [comment]
I am closing this because I was unable to replicate the issue and more details were not provided. Feel free to reopen if problem is still present in the [latest version](https://www.pkcs11admin.net/latest/).
